/**
 * The production build: everything Cloudflare Workers needs, in `dist/`.
 *
 * Nothing is crawled — the app is served live — so a build is three things:
 *
 * 1. **The client**, compiled exactly as `deno serve` compiles it (`compile.ts`), with every
 *    emitted module written under `dist/public/assets/` and each entrypoint's URL and preloads
 *    recorded in `dist/manifest.json`. `client/static/` goes to `dist/public/static/`, and the
 *    service worker and web manifest to the root, where their scope and URL have to be.
 * 2. **The server**, `worker.ts` and everything it imports, bundled into `dist/app.js`.
 * 3. **`dist/index.js`**, the module Wrangler deploys, handing the manifest to the bundled app.
 *
 * `dist/public/` is the Worker's Static Assets directory (`wrangler.jsonc`).
 */

import { clientDir, compileClient } from "./compile.ts";
import {
  ISLAND_ENTRIES,
  RUNTIME_ENTRY,
  type ScriptManifest,
} from "./scripts.ts";

const dist = new URL("../dist/", import.meta.url);
const pub = new URL("public/", dist);

await Deno.remove(dist, { recursive: true }).catch(() => {});
await Deno.mkdir(pub, { recursive: true });

async function write(url: URL, data: Uint8Array | string): Promise<void> {
  await Deno.mkdir(new URL(".", url), { recursive: true });
  if (typeof data === "string") await Deno.writeTextFile(url, data);
  else await Deno.writeFile(url, data);
}

async function copyDir(from: URL, to: URL): Promise<void> {
  for await (const entry of Deno.readDir(from)) {
    const source = new URL(entry.name + (entry.isDirectory ? "/" : ""), from);
    const target = new URL(entry.name + (entry.isDirectory ? "/" : ""), to);
    if (entry.isDirectory) await copyDir(source, target);
    else await write(target, await Deno.readFile(source));
  }
}

// 1. The client.
const assets = await compileClient();
let files = 0;
for (const path of new Set(assets.moduleUrls().values())) {
  const response = await assets.fetch(new Request(`http://build${path}`));
  if (!response?.ok) throw new Error(`could not read back ${path}`);
  await write(
    new URL(`.${path}`, pub),
    new Uint8Array(await response.arrayBuffer()),
  );
  files++;
}

const islands: string[] = [];
for await (
  const entry of Deno.readDir(new URL("islands/", `file://${clientDir}`))
) {
  if (entry.isFile && entry.name.endsWith(".tsx")) {
    islands.push(`islands/${entry.name}`);
  }
}
const manifest: ScriptManifest = {};
for (const path of [RUNTIME_ENTRY, ...islands.sort()]) {
  const { href, preloads } = await assets.getScriptEntry(path);
  manifest[path] = { href, preloads };
}
await write(new URL("manifest.json", dist), JSON.stringify(manifest, null, 2));

const staticDir = new URL("../client/static/", import.meta.url);
await copyDir(staticDir, new URL("static/", pub));
for (const name of ["sw.js", "manifest.webmanifest"]) {
  await write(
    new URL(name, pub),
    await Deno.readFile(new URL(name, staticDir)),
  );
}
console.log(
  `client: ${files} modules, ${
    Object.keys(manifest).length
  } entries (${ISLAND_ENTRIES})`,
);

// 2. The server.
const result = await Deno.bundle({
  entrypoints: [new URL("./worker.ts", import.meta.url).pathname],
  outputPath: new URL("app.js", dist).pathname,
  platform: "browser",
  format: "esm",
  minify: true,
  external: ["node:*"],
});
for (const warning of result.warnings) console.warn(warning.text);
if (!result.success) {
  for (const error of result.errors) console.error(error.text);
  Deno.exit(1);
}
console.log("server: dist/app.js");

// 3. The entry Wrangler deploys.
await write(
  new URL("index.js", dist),
  `// Generated by server/build.ts.
import createWorker from "./app.js";
import manifest from "./manifest.json";

export default createWorker(manifest);
`,
);
console.log("entry: dist/index.js");

// `deno run` would otherwise wait on the asset server's bundler.
Deno.exit(0);
